# temperature: hot / cold
# type: main / side
# time: breakfast / lunch / dinner

products:
    - name: Fusilli
      type: food
    - name: Pesto Genovese
      type: food
    - name: Minutensteaks
      type: food
    - name: Heringsfilet
      type: food

components:
    - name: Minutensteaks
      type: main
      temperature: hot
      time: lunch
      ingredients:
        - [Minutensteaks, 0.190]
    - name: Pasta Pesto
      type: main
      temperature: hot
      time: lunch
      ingredients:
        - [Fusilli, 0.250]
        - [Pesto Genovese, 0.095]
    - name: Heringsfilet
      type: main
      temperature: cold
      time: dinner
      ingredients:
        - [Heringsfilet, 0.200]

stores:
    - name: Kaufland
      products:
        # kg, EUR
        - [Fusilli, 0.5, 0.47]
        - [Pesto Genovese, 0.19, 0.96]
        - [Minutensteaks, 0.475, 2.28]
        - [Heringsfilet, 0.200, 0.97]

description:
    max_budget: 25.00
    start: Sunday
    days: 7
    default: [hot lunch, cold dinner]
    override:
        Monday: [hot lunch]
        Wednesday: [hot lunch]
    count:
        types:
            side:
                min: 2
                max: 3
        components:
            Minutensteaks:
                min: 4
                max: 4
